name: Deploy VoidTales Portal

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # 1. Definiere ein Environment fÃ¼r den Job
    environment:
      name: production
      url: https://portal.voidtales.win/

    steps:
      - name: ðŸ“¥ Checkout Code
        uses: actions/checkout@v3
        with:
          # Stellt sicher, dass das Projekt in den richtigen Ordner geklont wird
          path: 'voidtales-portal'

      - name: ðŸ”§ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: ðŸ“¦ Cache Node.js modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: voidtales-portal/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/voidtales-portal/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: ðŸ§© Install Dependencies
        run: npm install
        working-directory: './voidtales-portal'

      - name: ðŸ”¨ Build Nuxt Project
        run: npm run build
        working-directory: './voidtales-portal'

      - name: ðŸ”¨ Start Nuxt Project
        run: pm2 start ecosystem.config.cjs
        working-directory: './voidtales-portal'